/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.spektacle.spring.data.jdbc

import org.springframework.data.relational.core.dialect.AnsiDialect
import org.springframework.data.relational.core.dialect.ArrayColumns

class IRISDialect : AnsiDialect() {

    override fun getArraySupport(): ArrayColumns {
        return ArrayColumns.Unsupported.INSTANCE
    }

    companion object {
        val INSTANCE: IRISDialect = IRISDialect()
    }
}
